docs/src/project.md, src/DrWatson.jl, src/saving.jl, src/saving_tools.jl, test/runtests.jl, test/stools_tests.jl
Currently this function "fails" because for example if a key of the dictionary `d` is a string then the function expands over it and makes the entries `Char`:
```
julia> d = Dict(:a => [1, 2, 3], :b => 4, :c => "test")
Dict{Symbol,Any} with 3 entries:
:a => [1, 2, 3]
:b => 4
:c => "test"
julia> dict_list(d)
12-element Array{Dict{Symbol,Any},1}:
Dict(:a=>1,:b=>4,:c=>'t')
Dict(:a=>2,:b=>4,:c=>'t')
Dict(:a=>3,:b=>4,:c=>'t')
Dict(:a=>1,:b=>4,:c=>'e')
Dict(:a=>2,:b=>4,:c=>'e')
Dict(:a=>3,:b=>4,:c=>'e')
Dict(:a=>1,:b=>4,:c=>'s')
Dict(:a=>2,:b=>4,:c=>'s')
Dict(:a=>3,:b=>4,:c=>'s')
Dict(:a=>1,:b=>4,:c=>'t')
Dict(:a=>2,:b=>4,:c=>'t')
Dict(:a=>3,:b=>4,:c=>'t')
```
In general it is difficult to predict whether any arbitrary used-defined type should be iterable or not in this case. However …
=> Initial dict_list function

CHANGELOG.md, src/saving_files.jl, src/saving_tools.jl, test/savefiles_tests.jl, test/stools_tests.jl
Closes #35
These macros are able to record the source file that called them, as well as the line of code they were called at. As a result, they do the same as `tag!, tagsave` but record additional reproducibility information.
=> Add macros @tag and @tagsave

src/saving_tools.jl, test/stools_tests.jl
I came across the following minor incovenience:
```julia
julia> d = Dict(:x => [1], :y => [2.0])
Dict{Symbol,Array{T,1} where T} with 2 entries:
:y => [2.0]
:x => [1]
julia> dict_list(d)
1-element Array{Dict{Any,Any},1}:
Dict(:y=>2.0,:x=>1)
```
The return type of `dict_list` is a `Vector` of `Dict{Any,Any}`, when the type of the key (at least) should be able to be inferred. It turns out that it is due to merging the `iterable_dict` with the `non_iterable_dict` inside the `dict_list` method, where `non_iterable_dict` is an empty `Dict{Any,Any}`.
The fix is simply to check for emptiness, and only merging if they are both non-empty. Then, we get the expected output:
```julia
julia> dict_list(d)
1-element Array{Dict{Symbol,Real},1}:
Dict(:y=>2.0,:x=>1)
```
I've added some corresponding tests, …
=> Improve typing on return type of `dict_list`

CHANGELOG.md, docs/src/name.md, docs/src/real_world.md, src/naming.jl, test/naming_tests.jl
This PR allows `savename` to be used a bit more flexibly with structs that contain containers within them. 
(see docs)
=> Expand functionality for savename

CHANGELOG.md, src/saving_files.jl, test/savefiles_tests.jl
It is really convenient to immediately access the path a filed is saved at with produce_or_load. This change takes care of that.
Heavily breaking, but what can you do. This is the life. I am a bit unhappy about the return value, which can be a file or `nothing`, but I think it is advantageous to not always have to load very large files...
=> new return value for produce_or_load

.gitignore, CHANGELOG.md, docs/src/name.md, src/DrWatson.jl, src/naming.jl, test/naming_tests.jl
Implements a function to parse the savename into a dict and extract the pre- and suffix (#38).
I thought of some special cases
- prefix is a path containing a folder named something like "a=1.23_mode=double"
- key or value contains `connector` (no precise solution, I'm adding them to the value part)
- last number is a float so the "." doesn't denote the start of the suffix
=> Add function for reverse engineering savename

CHANGELOG.md, docs/src/name.md, src/naming.jl, test/naming_tests.jl
Implements #60. Turned out to be not just calling `@dict` and then `savename`. The `args` need to be escaped before the `dict` macro call which messes up the variable names.
Closes #60
=> Add @savename macro

src/naming.jl, test/naming_tests.jl
I noticed today that `parse_savename` throws a pretty inconclusive error msg when a `connector` appears after the last `=`.
```
julia> parse_savename("prefix_a_1=1_b=mode_a")
ERROR: MethodError: no method matching iterate(::Nothing)
```
```
julia> parse_savename("prefix_a_1=1_b=mode_a")
ERROR: Savename cannot be parsed. There is a '_' after the last '='. Values containing '_' are not allowed when parsing.
```
Also #38 can be closed
=> Add proper error msg to `parse_savename`

.gitignore, CHANGELOG.md, Project.toml, docs/src/save.md, src/DrWatson.jl, src/saving_tools.jl, test/project_tests.jl, test/stools_tests.jl
I use annotated Git tags (`git tag -a v0.1.2`) to mark the stage of the developments even in my research repositories and then `git describe` gives a nice human readable representation of the HEAD. I think it would be nice if this was used in `tagsave` too.
For example if `git describe` spits out this: `12.0.0-alpha.1-8-g6f60bd1d-D`, I immediately know that it's 8 commits ahead of version 12.0.0-alpha.1, it's a dirty repository (`-D`) and the last commit is `6f60bd1d`.
My PR just falls back to the commit hash if there is no annotated tags and also preserves the `_dirty` suffix. Of course now the `current_commit()` is not really referring to the `current_commit`, so the naming should be discussed also.
What do you think?
=> Use git describe if possible for tagging

CHANGELOG.md, src/saving_tools.jl, test/stools_tests.jl
When doing, e.g., `gitdescribe(".")` and "." is a subdirectory to the topmost gid-dir (where `.git` is), then currently:
```
julia> gitdescribe(".")
┌ Warning: The directory ('.') is not a Git repository, returning `nothing` instead of the commit ID.
└ @ DrWatson ~/.julia/dev/DrWatson/src/saving_tools.jl:46
```
With this PR it "correctly" returns the hash of the repo.
As I haven't gotten around to trying DrWatson out, I don't know whether this is an improvement or not.  Also, if #80 gets merged, one more `GetRepo` -> `GetRepoExt` needs to be done.
=> Replace GitRepo -> GitRepoExt to get repo also when using sub-dirs

CHANGELOG.md, Project.toml, src/defaults/project_structure.txt, src/project_setup.jl
Well, it just so happens that every month I find a new reason to regret merging #43. No more I will live with such regrets, I am reverting it!
---
The motivation is simple: this "test" directory is clearly targeting a Julia package. I am not sure how many scientists write consistent checks for their actual projects. I am for sure not one of them. The advantage of not having a test directory will be great: hopefully people will not tend to think that DrWatson is about Julia packages.
=> Remove test directory from `initialize_project`

CHANGELOG.md, Project.toml, src/DrWatson.jl, src/saving_files.jl, src/saving_tools.jl, test/runtests.jl, test/savefiles_tests.jl, test/stools_tests.jl
Implements #84. I'll also add #83, so this is still a draft.
The problems with having kw and non-kw versions are the following:
**Methods:** The definition of the kw-function also creates a method without the keywords. However, this method is also defined by the optional args function defintion. So on `using` you get a warning that the method is overwritten. My solution here is to define one additional argument, in the non-kw function, as mandatory. So dispatch works like this now:
- If this argument is not given -> dispatch on the kw-version
- If it is given -> dispatch on the non-kw-version
**Macros:** This one is a little tricky. During dispatch one can't tell if the passed `args...` to the macro are kw-definitions or not eg:
```
julia> :(@__DIR__)|>typeof
Expr
julia> :(x=10)|>typeof …
```
=> Improve tag functions and macros

CHANGELOG.md, Project.toml, docs/make.jl, docs/src/real_world.md, src/DrWatson.jl, src/project_setup.jl, test/project_tests.jl
Alright, so here I am both writing some useful docs, as well as trying to add a new feature. So, when reading the docs you will see why I find this useful. I make some projects (that are very specific and thus I always use the same packages/etc.) usable modules.
Now, what I am trying to extend is to be able to create a macro so that 
```julia
@quickactivate ProjectName
```
somehow expands to
```julia
quickactivate(@__DIR__, string(ProjectName)
using ProjectName
```
I have a suspicion that this is not possible to do really with `ProjectName`, because this is undefined when we call the macro... BUT, it is certainly possible to do using Symbols, i.e.
```julia
@quickactivate :ProjectName
```
the problem is, I haven't succeeded yet in doing so...  I am testing the current code in my own …
=> making usable module docs

src/naming.jl
This PR will show a warning when a path separator is present in the `prefix` parameter of the `savename` function, which may lead to incompatibility on different OS.
In addition, the corresponding examples in the docs were removed and the docstring updated to encourage the usage of the `*dir` methods.
=> Show warning when savename-prefix contains path separators. Closes #132

CHANGELOG.md, Project.toml, docs/src/save.md, src/saving_tools.jl, test/customize_savename.jl
Closes #138 .
Adds a new function `struct2dict`.
Added tests to `test/customize_savename.jl`  which seem to run okay.
```
$ ~/julia/julia test/customize_savename.jl 
┌ Warning:     Path separators in `savename` prefixes may break reproducibility on other OS.
│     The recommended way is using the `*dir()` methods or `joinpath` with
│     `savename` (e.g. `datadir("path", "to", "folder", savename("prefix", data))`).
└ @ DrWatson ~/DrWatson.jl/src/naming.jl:87
```
=> add new function struct2dict

CHANGELOG.md, Project.toml, src/DrWatson.jl
I noticed that it's currently not possible to use `wsave` with keyword arguments (needed, e.g., when setting the output resolution in CairoMakie: https://github.com/JuliaPlots/CairoMakie.jl#saving).
=> Support keyword arguments in `wsave` and `wload`

Project.toml, src/naming.jl, test/naming_tests.jl
Currently `savename` errors when you try to use it with `Inf` or `NaN` floats.
(The issue happens when trying to round to a certain number of digits)
=> Make savename work with `Inf` and `NaN` values

paper/LICENSE, paper/paper.bib, paper/paper.md
The JOSS Paper Review service to generate the PDF using their template can be found here: https://whedon.theoj.org/
Open points:
=> Add JOSS Paper

Project.toml, src/project_setup.jl
Added an optional argument `placeholder` to enable cloning of the project structure. It simply adds a hidden file `.placeholder` in all folders and commits it.
=> Create project structures that can be cloned as is

paper/paper.bib, paper/paper.md
A DOI from a copied bib-file had `http...` in it which is now removed and I splitted the introductory in two parts "Summary" and "Statement of need" as required by the JOSS reviewers.
=> A few fixes to fulfil JOSS requirements

src/dict_list.jl
Hey there,
today when I went through the `Running & Listing Simulations` I noticed some typos that I removed. 
The `lookup_candidate` ref isn't really a typo but since the docs don't include this function, the ref was directing to 404.
Cheers
Max
=> cleaned some typos in the docs

CHANGELOG.md, Project.toml, src/result_collection.jl, test/update_results_tests.jl
Addresses #116 
Removes `datadir()` from the path entry before adding a row to the collected results dataframe. I can change it to remove only `projectdir` instead, using the data directory just seemed more natural to me.
=> Use relpath in collect_results!

CHANGELOG.md, Project.toml, src/naming.jl, test/naming_tests.jl
Sometimes, it's nicer to have names sorted in a particular order with more important parameters at the front. This makes it easier when viewing outputs in a file manager, too. 
Obviously, this only works for types like NamedTuple that are sorted.
=> Add a "sort" option to `savename`

CHANGELOG.md, Project.toml, src/saving_files.jl
This simple 2-line PR relaxes the type constraints on 
what is accepted as a path.
This adds generic compatibility to custom filepath structures.
closes #229
=> Relax type constraint

CHANGELOG.md, Project.toml, src/DrWatson.jl, src/naming.jl, test/customize_savename.jl, test/naming_tests.jl
Closes #163, closes #158
Okay, the hope here is to address all concerns and requests of #163. It also removes the "Float -> Integer" existing convention of `savename`, which in hindsight was a bad idea.
Currently work in progress.
=> Rounding and scientific notation in `savename`

Project.toml, src/result_collection.jl, test/savefiles_tests.jl, test/update_results_tests.jl
`collect_results!` is not working with JLD2 files, as the resulting DataFrame is saved in a Dictionary with Symbol keys. Changing this to a String key should have no impact to users, as the base Dictionary is not returned at all.
=> Fix loading of results collection with JLD2

src/saving_tools.jl
I use `tag!` to give me information about several repositories that are part of my project. Hence, it's convenient for me to know which one the warning refers to. I think the warning benefits from this additional information. I also think it isn't too long.
This change is very minor and obviously doesn't break anything (`gitpath` is already being interpolated into another warning in the same method). Hence, I do not bother to change other files and adjust version information or the like.
=> "dirty"-warning in `gitdescribe` includes `gitpath`

docs/src/workflow.jl
New to GitHub contributing, new Julia fan, loved the JuliaCon presentation for DrWatson!
Anyway, looking into using DrWatson and noticed a broken link and though the first line in this doc page could use a link out for other noobs like me.
=> Add Julia project manager link, fix a broken link in docs

CHANGELOG.md, Project.toml, src/defaults/gitattributes.txt, src/project_setup.jl
Improve cross-platform compatibility and robust handling of binaries, etc with git using .gitattributes.
=> Add .gitattributes at project initialization

docs/src/index.md
Bibliography.jl moved to Humans-of-Julia GitHub org a few months ago! Thanks for the reference by the way :)
=> Update the reference to Bibliography.jl

CHANGELOG.md, Project.toml, src/project_setup.jl, test/project_tests.jl, test/stools_tests.jl
Closes #264
Okay, the idea is pretty simple. A template is just a vector of strings or pair=>vector{string}. Seems pretty clean to me, easy to adopt, easy to change. 
Any ideas/recommendations for a couple more pre-made templates are welcomed.
=> Allow templates in `initialize_project`

Project.toml, src/saving_files.jl
Hi,
I noticed that `produce_or_load` crashes when file saving fails, because of a lonely `*`. This fixes the issue.
=> Fix crash of `produce_or_load` when saving file fails.

Project.toml, src/project_setup.jl
If `findproject` doesn't find its requested directory, it tries to issue a warning, but fails because the input variable name was evidently changed from `path` to `dir`.   This fixes it in the warning and the docstring.
=> Fix variable name in `findproject`

Project.toml, src/project_setup.jl
Currently, with the default parameters, `initialize_project` makes the project a git repo.  As part of that process, it checks the git config *of the repo* for the options `user.name` and `user.email`.  Unless the repo existed already and had those options set explicitly, these options will not exist, so `initialize_project` just sets them to `"DrWatson"` and `"no@mail"`, respectively.  I'm guessing that the reason for this is to ensure that it can make an initial commit without any issues.
That makes some sense, but I think it makes more sense to check the global config before setting those options.  If they exist in the global config (or already in the local config), they shouldn't be set locally.  The initial commit should still work just fine, using those global settings.
=> Fall back on global git config

CHANGELOG.md, Project.toml, src/saving_files.jl, test/savefiles_tests.jl
This allows the enabling of compression with JLD2 for example. We use simple keyword propagation in the functions `tagsave`, `safesave` and `tmpsave`. For `produce_and_load` we introduce a new keyword argument `wsave_kwargs` because it already uses keyword propagation to `savename`.
This addresses #274 allowing the pass through of compression options.
=> Allow keyword pass through to wsave

src/naming.jl, test/naming_tests.jl
To make the `savename` `accesses` keyword syntax easier, allow
automatic conversion of `String` keys to `Symbol`s when working with
containers other than `Dict`s. Explicitly continue to allow `String`
keys for `Dict`s.
Includes tests for `String` key to `Symbol` conversion when handling a
struct, and `String` key pass through when handling a `Dict`.
Closes #259.
=> Automatically convert `String` keys to `Symbol`s in `access`.

CHANGELOG.md, Project.toml, docs/src/save.md, src/saving_files.jl, src/saving_tools.jl, test/savefiles_tests.jl, test/stools_tests.jl
Introduces a macro version of `@produce_or_load` that saves the source
file name and line number of the calling line, similar to `@tagsave`.
Adds tests that check if the appropriate file name and line number was
saved.
This closes #136 .
=> Add macro `@produce_or_load` to add source file and line tag

Project.toml, src/DrWatson.jl, src/dict_list.jl, src/naming.jl, src/saving_files.jl, src/saving_tools.jl, test/stools_tests.jl
Anywhere where functions required the input to be a `::Dict{K,T}` were changed to `::AbstractDict{K,T}` to allow for OrderedDicts.
The only place this was not changed was in the project_setup where it gets the `pkg["name"]` because that returns a Dict.
- Added an optional kwarg `order` argument to `struct2dict` to return an OrderedDict (default is false), where order refers to insertion order. If a set of OrderedDicts is used with `dict_list` an OrderedDict should be returned.
- added a test for using dict_list with an Ordered Dict
- `OrderedDict` from DataStructures is also exported from DrWatson.
- `checktagtype!` will also return a regular Dict.
Fixes #278 at the most basic level.
=> Allow for OrderedDicts to be passed to dict_list and other similar functions

Project.toml, src/naming.jl, test/stools_tests.jl
Missed the addition of supporting `OrderedDict` in `ntuple2dict with pull request #283.
=> Added support for returning `OrderedDict` when using `ntuple2dict`.

CHANGELOG.md, Project.toml, src/result_collection.jl, test/update_results_tests.jl
I often re-run a computation or data analysis that results in some updated data files. But this isn't propagated through to the results database by `collect_results!` because that only looks for new files but leaves entries for files that have already existed but are now changed alone. The only way to trigger an update is to delete the results database. However, I often run some moderately lengthy computation in `collect_results!` using the `special_list` argument and want to avoid doing that for the whole collection of data files.
This PR adds an `update` keyword argument to `collect_results!` (defaulting to `false`). If `true` it actively syncs an existing results database with the raw data file collection. In particular, when it encounters files whose `mtime` is younger than the result …
=> Introduce `update` argument to `collect_results!` to sync results files.

Project.toml, src/saving_files.jl, test/savefiles_tests.jl
Suppose you would like to save a custom data structure as a directory containing several files (or other directories). This fixes the `wsave` machinery for that use case.
I am working on a cluster and my result type holds `Future`s (non-cached, i.e. having `fut.v == nothing`, though I'm considering to move to [DeferredFutures.jl](https://github.com/invenia/DeferredFutures.jl)) to data on different nodes. I would like to have each node/worker write a separate file to disk, such that I don't need to transfer all the data to the managing process.
If there is anything I missed, or you've got any suggestions, I'm all ears. 🙂
=> Fix recursively_clear_path for directories

src/DrWatson.jl, src/saving_files.jl, src/saving_tools.jl, test/stools_tests.jl
If `get(ENV, ...)` returns the non-default value, that will be a `String`. Therefore, it first has to be parsed as a `Bool`.
=> Fix ENV usage

Project.toml, src/saving_tools.jl, test/stools_tests.jl
such that it matches the output of `git describe --dirty`. Do so by
adding a keyword argument to `gitdescribe()` having that new default.
Fix #306
=> Change dirty suffix from `_dirty` to `-dirty`

src/saving_files.jl
If using JLD2, this allows to use the name - value signature of fileio_save.
Since wsave already does this, the lack of ... here is probably just an oversight.
=> Make safesave use the full signature of wsave

CHANGELOG.md, Project.toml, docs/src/index.md, docs/src/real_world.md, docs/src/workflow.jl, src/DrWatson.jl, src/result_collection.jl, src/saving_files.jl, test/savefiles_tests.jl
Alright, so this PR kinda solves my problems I had with really wanting to use `produce_or_load`, but also having too many, or too complicated, simulation parameters. I guess it is a simple inbetween step until DrWatson has some proper way to manage metadata/configuration "files". The discussion here https://github.com/JuliaDynamics/DrWatson.jl/issues/316 and the PR https://github.com/JuliaDynamics/DrWatson.jl/pull/333 are relevant.
My intermediate solution is to allow arbitrary functions in `produce_or_load` that take as an input the `config` container, and return a hopefully unique string for it. In my personal workflow I am using `objectid`, but I haven't tested it extensively to see really how unique or safe its output is. When DrWatsonSim functionality is in, the change in this PR …
=> Allow arbitrary functions to extract name from configuration in `produce_or_load`

Project.toml, src/defaults/gitignore.txt
The current default gitignore ignores all folders and files with names in "Folders to ignore"
This PR suggests only ignoring those names if occurring at the top level.
=> Make default gitignore only ignore folders at the top level

src/project_setup.jl
This is my fix #251.
As far as I can tell the problem was that [GitReference()](https://github.com/JuliaDynamics/DrWatson.jl/blob/main/src/project_setup.jl#L308) needed the prefix `LibGit2.`.
This fixes the problem (for me) and the warning message no longer occurs.
The created project only has 1 branch named `main` even if global settings of the user are different.
=> Fix for Issue#251

src/project_setup.jl, src/result_collection.jl, test/update_results_tests.jl
This is my fix #181.
Using the mentioned `rstrip()` for the creation of the default value of `filename` in `result_colletion.jl` the described error will no longer occur.
By also adding `rstrip()` to `projectdir()` function, the error is also fixed if `collect_results!()` is called using defined variables using `datadir()` (as is done in `update_results_tests.jl`).
To demonstrate that, I included a test within `update_resluts_tests.jl` that checks if the bugged file is created.
In the case that the wrongly named and placed file is created, the test will remove it anyways, since it would interfere with the test regarding the dimensions of the dataframes (e.g. ` @test size(cres2) == (6, 7)`).
I hope you will find this helpful!
=> Fix to Issue#181

src/project_setup.jl, test/project_tests.jl
Converts output of `projectdir` to String. Added test for all *dir() functions whish is redundant when testing `projectdir()` directly. Happy to remove the extra test if you think it's unnecessary. Fixes #382. 
Passes all tests locally
=> Force convert of projectdir to String

CHANGELOG.md, Project.toml, src/saving_files.jl, test/savefiles_tests.jl
See #392 
I also created a test, but I was unable to test it locally. Each time I ran tests `BSON` package was uninstalled, and the lack of this package produced errors, and further tests were unable to be run. The issue might be with the system not making a distinction between a system package and a local one.
=> Removing double prefixes bug in produce_or_load

.github/workflows/ci.yml, .github/workflows/doccleanup.yml, Project.toml, src/defaults/ci.yml
While investigating https://github.com/JuliaDynamics/DrWatson.jl/issues/406 I noticed that most actions are not on the latest release version. It's not important to update them but I did it anyway.
It's also possible to automate this with dependabot:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
But it can become annoying to get pull requests from dependabot all the time.
=> Bumping GitHub action versions

.github/dependabot.yml
As discussed in https://github.com/JuliaDynamics/DrWatson.jl/pull/407 this PR adds [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) to DrWatson.jl to keep the GitHub actions up to date.
dependabot.yml added:
- Update actions monthly
=> Adding dependabot for GitHub actions

CHANGELOG.md, Project.toml, src/saving_files.jl
Added the ability to pass keyword arguments to `wload` within `produce_or_load` by defining a new kwarg called `wload_kwargs`. This works the same way as the existing functionality provided by `wsave_kwargs`. This is useful, for example, if you need to load a data type from file but the type definition has changed. You can pass a [typemap ](https://juliaio.github.io/JLD2.jl/dev/advanced/#Upgrading-old-structures-on-load) to JLD2 that instructs it how to rebuild the object. This is not possible in the current implementation of `produce_or_load` because there is no way to pass kwargs to `wload`. This pull request makes it possible. 
The default types for both `wsave_kwargs` and `wload_kwargs` are now empty named tuples. This seems like the more natural choice than an empty `Dict` which …
=> Add `wload kwargs` to `produce_or_load`

docs/src/real_world.md
Triggered by the [post on discourse](https://discourse.julialang.org/t/drwatson-common-code-as-module-issue/115203) where a user had issues with the conversion of their project into a package, I added a comment to the docs mentioning the need for a `name` in `Project.toml`
I also saw #397 and added some words about the advantages (can use Revise.jl) and disadvantages (frequent recompilation). I did not quite understand why this recompilation should take a long time, since the dependencies should not be recompiled anew AFAIK. But I mentioned it nonetheless.
I did no changes beyond the documentation, so please consider whether this PR fixes #397.
Please read the changes and let me know where I should rephrase things. I tried to stick to the style of the rest of the page.
=> Expand section "making your project a usable module"

CHANGELOG.md, Project.toml, src/result_collection.jl, test/update_results_tests.jl
The changes in this branch are a follow up from a previous pull request based on commit 6e6ff07 in PR #421. In that PR there were issues with whitespace changes inadvertantly coming from the autoformatter in vscode. Reverting the whitespace changes proved to be more difficult than anticicpated.
So to resolve this, this branch was created and a new PR will be created from it. The whitespace issues are gone but all the feedback and changes from the original PR are retained.
The commit makes the following changes.
- add the `load_function` kwarg to `collect_results`. This allows customizing how data is loaded from file before being processed into a dataframe by `collect_results`.
- add a test to `update_result_tests.jl`
- update docstring of `collect_results`
- increase package version to …
=> implement `load_function` kwarg for collect_results!

src/saving_tools.jl
The `gitpatch` function sometimes hangs for large git diffs. This seems to be happening because the `read_stdout_stderr` function is writing to the `out` and `err` pipes, but no task is reading from them, so they fill up, and the process locks up waiting to write more data.
This change spawns separate tasks to read from the `out` and `err` pipes, thus avoiding the deadlock.
The Julia compat for this package is set to 1.0, so I opted to use `@async` instead of `Threads.@spawn`.
Fixes #300
=> Avoid deadlock when reading stdout and stderr from commands
