JuliaDynamics/DrWatson.jl

docs/src/savenames.md
src/naming.jl
test/naming_tests.jl

Which does the same as `@dict` but for named tuples. Also improve docs a bit.

Add `@ntuple` macro

---

LICENSE
src/naming.jl
test/naming_tests.jl

add conversion between NT and Dict

---

README.md
docs/src/index.md
docs/src/project.md
docs/src/savenames.md
src/defaults/project_structure.txt
src/naming.jl
test/naming_tests.jl

Allow suffix/prefix in `savename`, make `@dict` use Symbol as key type (because we will be using BSON), and some doc improvements

Suffix, Symbol, Docs

---

docs/src/savenames.md
src/naming.jl
test/naming_tests.jl

Add custom prefix and recursive access

---

.travis.yml
docs/make.jl
docs/src/index.md
docs/src/name&save.md
docs/src/real_world.md
test/REQUIRE
test/customize_savename.jl
test/runtests.jl

Add test and documentation for customizing savename

---

REQUIRE
docs/src/name&save.md
src/DrWatson.jl
src/result_collection.jl
src/saving_files.jl
src/saving_tools.jl
test/REQUIRE
test/savefiles_tests.jl
test/update_results_tests.jl

change to FileIO

---

docs/src/index.md
docs/src/name&save.md
src/saving_files.jl
src/saving_tools.jl
test/savefiles_tests.jl

Second try without all the mess from the other branch

backup saving v2

---

docs/src/real_world.md
docs/src/run&list.md
src/result_collection.jl
test/update_results_tests.jl

The only thing I have not done is add a keyword `reprocess = false` , like it was discussed in the last comment of #28.
Thing is, I don't actually know how to do this. Maybe we can merge this and add this as a post-beta feature request. Because besides this nothing else is holding back a beta release.
Closes #28

iip & oop collect_results

---

src/defaults/project_structure.txt
src/defaults/runtests.jl
src/project_setup.jl

Addressing #40 ;)
Now that I think about it, I'm not sure if `testdir()` will ever actually be useful...

Add test directory to default project

---

CHANGELOG.md
Project.toml
docs/src/real_world.md
docs/src/run&list.md
docs/src/save.md
src/defaults/project_structure.txt
src/saving_files.jl
test/project_tests.jl
test/stools_tests.jl

[WIP] Temporary save results of dict_list

---

CHANGELOG.md
Project.toml
src/naming.jl
test/customize_savename.jl

This PR (I believe) improves the functionality around `default_prefix`

new specification for default_prefix

---

src/defaults/gitignore.txt

Adds comments
Ignores LuaLaTeX and BibTeX artifacts as well

Update default gitignore

---

CHANGELOG.md
Project.toml
docs/src/project.md
docs/src/real_world.md
src/DrWatson.jl
src/naming.jl
src/project_setup.jl
src/saving_files.jl
test/customize_savename.jl
test/naming_tests.jl
test/project_tests.jl
test/update_results_tests.jl

This implements methods for the path accessing functions which accepts subdirectories as arguments, as initially proposed by @JonasIsensee in https://github.com/JuliaDynamics/DrWatson.jl/issues/47
Closes #47

Extend path accessing functions to accept arguments

---

src/result_collection.jl
test/update_results_tests.jl

I made the relevant changes. No more deprecation warnings.
Also slightly improved the tests to cover more possibilities.
closes #68

made changes for new api and improved tests

---

CHANGELOG.md
Project.toml
src/project_setup.jl
test/project_tests.jl

This is just a straightforward implementation using the hints in #10.
Closes #10

Warn user when projectdir is used and no project is active

---

CHANGELOG.md
src/naming.jl
src/saving_files.jl
test/savefiles_tests.jl

Closes #78 and improves `produce_or_load`

Improve prefix handling and documentation

---

CHANGELOG.md
docs/src/save.md
src/saving_files.jl
src/saving_tools.jl
test/savefiles_tests.jl
test/stools_tests.jl

Fixes #36.
Needs tests and documentation.

WIP: Generating and storing a patch

---

CHANGELOG.md
Project.toml
src/project_setup.jl

Included julia-compat

---

CHANGELOG.md
Project.toml
src/naming.jl
test/naming_tests.jl

Add scientific keyword to savename

---

CHANGELOG.md
Project.toml
src/project_setup.jl

Only use major.minor.patch for compat version

---

Project.toml
src/saving_files.jl
src/saving_tools.jl

better error handling

---

Project.toml
src/saving_tools.jl

Fix git diff for older git versions

---

Project.toml
src/result_collection.jl
test/update_results_tests.jl

Fix #104 Broken collect_results! when white_list is empty but special_list is not

---

Project.toml
src/project_setup.jl
test/project_tests.jl

Fix file permissions of initially created files

---

CHANGELOG.md
Project.toml
docs/src/save.md
src/DrWatson.jl
src/saving_files.jl

`wsave` and `wload` can now be overloaded

---

CHANGELOG.md
Project.toml
docs/src/project.md
src/project_setup.jl
test/update_results_tests.jl

remove infinite spam from QUACKTIVATE and add @quickactivate

---

CHANGELOG.md
src/project_setup.jl
test/project_tests.jl

`initialize_project(".")` resulted in a project named `.`.
This now gets the foldername

Fix name retrieval on init

---

CHANGELOG.md
Project.toml
docs/src/name.md
src/naming.jl
test/naming_tests.jl

Add `ignore` to `savename`

---

docs/make.jl

see https://github.com/JuliaDocs/Documenter.jl/pull/1180

Allow preview docs to be pushed on PRs

---

src/result_collection.jl
test/update_results_tests.jl

Fix collect_results! bug

---

CHANGELOG.md
Project.toml
docs/make.jl
docs/src/real_world.md
src/naming.jl
test/naming_tests.jl

Allow dates by default in `savename`

---

CHANGELOG.md
Project.toml
src/saving_tools.jl

https://github.com/JuliaDynamics/DrWatson.jl/issues/161

Add warning to gitpatch if git is not in PATH

---

paper/paper.bib

...sorry, the DOI of the original citation for Sumatra which I copy&pasted was missing, I had to add it manually...

Add DOI for Sumatra

---

CHANGELOG.md
Project.toml
src/project_setup.jl

That highlights reproducibility and instructs how to do it.

Better README in initialize_project

---

CHANGELOG.md
Project.toml
src/project_setup.jl

If you don't have a breakline before 0., the list doesn't start properly.

Correct breakline for README enumeration

---

paper/paper.md

Related to [JOSS review](https://github.com/openjournals/joss-reviews/issues/2673#event-3765935810)
I've made a few minor edits to the manuscript. A couple of additional points:
- I think it would also be good to mention in the `Comparison with existing software section`, where you discuss that many projects use multiple programming languages, that julia actually has really good interop with other languages. via eg PyCall and RCall.
- In the same section, I think cwl is orthogonal to the purpose of DrWatson. The idea with CWL and other pipeline-type software (see [this discourse](https://discourse.julialang.org/t/rfc-mr-phelps-a-distributed-workflow-orchestrator/) thread for a bunch of other examples) is the run the same analysis pipeline on lots of different datasets. There's obviously …

Paper review

---

paper/paper.md

I tried to make it a bit more clearer how we compare DrWatson with CWL. I think now it's a bit better, but let me know what you think.

Paper: CWL part improvement

---

CHANGELOG.md
Project.toml
src/dict_list.jl
test/stools_tests.jl

Fix dict_list wrongly promoting types (#199)

---

paper/paper.bib
paper/paper.md

Add ActivePapers

---

Project.toml
src/dict_list.jl

replace Set with unique!

---

paper/paper.md

Minor edits for clarity and style.

Minor edits

---

CHANGELOG.md
Project.toml
src/saving_tools.jl

Apply as patch still works: https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-apply.html

Add submodule diff to git patch

---

CHANGELOG.md
Project.toml
src/saving_files.jl
test/savefiles_tests.jl

Addressing https://github.com/JuliaDynamics/DrWatson.jl/issues/126

Support do block for `produce_or_load`

---

CHANGELOG.md
Project.toml
src/dict_list.jl
src/saving_tools.jl

Fix #223 and #224

---

CHANGELOG.md
Project.toml
docs/Project.toml
docs/make.jl
docs/src/project.md
docs/src/real_world.md
docs/src/workflow.jl
src/DrWatson.jl
src/result_collection.jl
src/saving_files.jl
test/savefiles_tests.jl
test/stools_tests.jl

replace bson with jld2

---

CHANGELOG.md
Project.toml
docs/src/save.md
src/DrWatson.jl
src/saving_files.jl
src/saving_tools.jl
test/savefiles_tests.jl
test/stools_tests.jl

QOL improvements on the what should be attempted to be tagged

---

Project.toml
src/project_setup.jl

add info about global DrWatson

---

CHANGELOG.md
Project.toml
docs/src/save.md
src/saving_tools.jl
test/stools_tests.jl

First try at addressing issue #263

Add `isdirty(gitpath = projectdir())` function

---

CHANGELOG.md
Project.toml
src/naming.jl
test/naming_tests.jl

update defaults for keyword arguments of `savename`

---

CHANGELOG.md
Project.toml
src/saving_files.jl
src/saving_tools.jl

Addresses but does not close issue #300

make storepatch false by default

---

Project.toml
src/saving_files.jl
test/savefiles_tests.jl

Fix produce_and_load bug

---

docs/src/real_world.md

one more not using @strdict

---

src/saving_files.jl

The current documentation
produce_or_load([path="",] config, f; kwargs...) -> file, s
is quite confusing. It should be
produce_or_load([path="",] config, f; kwargs...) -> data, filename
or
produce_or_load([path="",] config, f; kwargs...) -> data, file
See https://github.com/JuliaDynamics/DrWatson.jl/issues/315#issuecomment-1013920021, https://github.com/JuliaDynamics/DrWatson.jl/issues/315#issuecomment-1013934772
In principle, this only affects the documentation, but it seems like a
good idea to refactor the names of the variables in the code to be
consistent.

Refactor names of produce_or_load return values

---

CONTRIBUTING.md
docs/src/project.md
docs/src/real_world.md
src/dict_list.jl
src/project_setup.jl

Clean docs and docstrings

---

CHANGELOG.md
Project.toml
docs/src/real_world.md
docs/src/run&list.md
src/dict_list.jl
src/saving_tools.jl
test/stools_tests.jl

In this branch I will give it a go to implemented the feature described in #358. I have never programmed a macro so I will try to follow #169.  Advice from @sebastianpech is welcome!

Adding Derived type for parameter dependency

---

src/project_setup.jl

Typo Fixing

---

Project.toml
src/project_setup.jl

Revert #380

---

README.md

Ref https://github.com/JuliaDynamics/DrWatson.jl/pull/414

Replace monthly download count badge with total downloads badge

---

docs/src/real_world.md

I changed the parameters in the example  real_world (produce_or_load) in the documentation.

Update real_world.md produce_or_load parameter
